# Generated by Django 3.0.5 on 2020-04-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
