# Generated by Django 3.0.5 on 2020-04-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0003_auto_20200403_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='current_location',
        ),
    ]
