# Generated by Django 3.0.5 on 2020-04-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0004_remove_packages_current_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='sender',
        ),
    ]
