# Generated by Django 3.0.5 on 2020-04-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0005_auto_20200403_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='package_type',
        ),
        migrations.AddField(
            model_name='packages',
            name='package_description',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
