# Generated by Django 3.0.5 on 2020-04-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0007_auto_20200403_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='package_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.branches')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.Packages')),
            ],
        ),
    ]
