# Generated by Django 3.0.3 on 2020-04-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0012_historicalpackages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpackage_history',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='historicalpackage_history',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpackage_history',
            name='package_ID',
        ),
        migrations.RemoveField(
            model_name='historicalpackages',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpackages',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='historicalpackages',
            name='sent_to',
        ),
        migrations.DeleteModel(
            name='Historicalbranches',
        ),
        migrations.DeleteModel(
            name='Historicalpackage_history',
        ),
        migrations.DeleteModel(
            name='HistoricalPackages',
        ),
    ]
