# Generated by Django 3.0.3 on 2020-04-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0015_location_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location_mark',
            old_name='package',
            new_name='package_ID',
        ),
    ]
