# Generated by Django 3.0.3 on 2020-04-11 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0016_auto_20200411_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_mark',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='postoffice.branches'),
        ),
        migrations.AlterField(
            model_name='location_mark',
            name='package_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.Packages'),
        ),
    ]
