# Generated by Django 3.0.5 on 2020-04-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0020_auto_20200412_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='last_sent',
            field=models.DateField(null=True),
        ),
    ]
