# Generated by Django 3.0.5 on 2020-04-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0021_sender_last_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sender',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
